[package]
authors = ["Bryant Luk <code@bryantluk.com>"]
description = "A distributed hash table node"
edition = "2024"
include = [
  "src/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]
license = "MIT OR Apache-2.0"
name = "waynode"
readme = "README.md"
repository = "https://github.com/bluk/waynode"
rust-version = "1.85.0"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
axum = "0.8.1"
bt_bencode = "0.8"
clap = { version = "4.4.7", features = ["derive", "env"] }
cloudburst = { git = "https://github.com/bluk/cloudburst", branch = "next" }
hyper = "1.0.1"
hyper-util = { version = "0.1.1", features = ["tokio", "server-auto", "http1", "http2"] }
rand = "0.10"
serde = { version = "1", default-features = false }
serde_bytes = "0.11"
serde_derive = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
thiserror = "2.0"
tokio = { version = "1.25.0", features = ["macros", "net", "rt", "rt-multi-thread", "signal"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.11", features = ["timeout", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
hex-literal = "1.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = "0.7.0"
tracing-journald = "0.3.0"
